
TG_CAT_TAILORING = "Tailoring";

TG_DB_TAILORING = {
    -- TAILORING --
    { tag = 165703,   name = "Breath of Bwonsamdi",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 158378,   name = "Embroidered Deep Sea Satin",  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 152577,   name = "Deep Sea Satin",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 152576,   name = "Tidespray Linen",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 162461,   name = "Sanguicell",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124124,   name = "Blood of Sargeras",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 130183,   name = "Shadowruby",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 151568,   name = "Primal Sargerite",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 152668,   name = "Expulsom",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 162460,   name = "Hydrocore",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 165948,   name = "Tidalcore",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124440,   name = "Arkhana",                     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 127004,   name = "Imbued Silkweave",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124106,   name = "Felwort",                     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 127759,   name = "Felblight",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 111556,   name = "Hexweave Cloth",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 113262,   name = "Sorcerous Water",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 113263,   name = "Sorcerous Earth",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 113264,   name = "Sorcerous Air",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 118472,   name = "Savage Blood",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 120945,   name = "Primal Spirit",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 109119,   name = "True Iron Ore",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 109126,   name = "Gorgrond Flytrap",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 110609,   name = "Raw Beast Hide",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 123918,   name = "Leystone Ore",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124113,   name = "Stonehide Leather",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124115,   name = "Stormscale",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124437,   name = "Shal'dorei Silk",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124438,   name = "Unbroken Claw",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 124439,   name = "Unbroken Tooth",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 127037,   name = "Runic Catgut",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 127681,   name = "Sharp Spritethorn",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 142335,   name = "Pristine Falcosaur Feather",  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 151567,   name = "Lightweave Cloth",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 159959,   name = "Nylon Thread",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 76061,    name = "Spirit of Harmony",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 80433,    name = "Blood Spirit",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 82447,    name = "Imperial Silk",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 94289,    name = "Haunting Spirit",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 98619,    name = "Celestial Cloth",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 102218,   name = "Spirit of War",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 82441,    name = "Bolt of Windwool Cloth",      cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 111557,   name = "Sumptuous Fur",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 72988,    name = "Windwool Cloth",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 71998,    name = "Essence of Destruction",      cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52078,    name = "Chaos Orb",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 54440,    name = "Dreamcloth",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52325,    name = "Volatile Fire",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52326,    name = "Volatile Water",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52327,    name = "Volatile Earth",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52328,    name = "Volatile Air",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52329,    name = "Volatile Life",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 52555,    name = "Hypnotic Dust",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 53010,    name = "Embersilk Cloth",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 53643,    name = "Bolt of Embersilk Cloth",     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36919,    name = "Cardinal Ruby",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36922,    name = "King's Amber",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36925,    name = "Majestic Zircon",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36934,    name = "Eye of Zul",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22682,    name = "Frozen Rune",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 34052,    name = "Dream Shard",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36930,    name = "Monarch Topaz",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 41593,    name = "Ebonweave",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 41594,    name = "Moonshroud",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 41595,    name = "Spellweave",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 43102,    name = "Frozen Orb",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 45087,    name = "Runed Orb",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 47556,    name = "Crusader Orb",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 49908,    name = "Primordial Saronite",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 69237,    name = "Living Ember",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36908,    name = "Frost Lotus",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 38425,    name = "Heavy Borean Leather",        cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 30183,    name = "Nether Vortex",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36784,    name = "Siren's Tear",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 34055,    name = "Greater Cosmic Essence",      cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 35622,    name = "Eternal Water",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 35624,    name = "Eternal Earth",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 35625,    name = "Eternal Life",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 35627,    name = "Eternal Shadow",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36783,    name = "Northsea Pearl",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 36860,    name = "Eternal Fire",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 41511,    name = "Bolt of Imbued Frostweave",   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 37701,    name = "Crystallized Earth",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 37702,    name = "Crystallized Fire",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 37704,    name = "Crystallized Life",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 42253,    name = "Iceweb Spider Silk",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22450,    name = "Void Crystal",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21845,    name = "Primal Mooncloth",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 24271,    name = "Spellcloth",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 24272,    name = "Shadowcloth",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 34664,    name = "Sunmote",                     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22794,    name = "Fel Lotus",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21844,    name = "Bolt of Soulcloth",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 33470,    name = "Frostweave Cloth",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 34054,    name = "Infinite Dust",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 38426,    name = "Eternium Thread",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 41510,    name = "Bolt of Frostweave",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21842,    name = "Bolt of Imbued Netherweave",  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 23571,    name = "Primal Might",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 23572,    name = "Primal Nether",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 32428,    name = "Heart of Darkness",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21884,    name = "Primal Fire",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21885,    name = "Primal Water",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21886,    name = "Primal Life",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22446,    name = "Greater Planar Essence",      cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22451,    name = "Primal Air",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22452,    name = "Primal Earth",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22456,    name = "Primal Shadow",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22457,    name = "Primal Mana",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 17010,    name = "Fiery Core",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 17011,    name = "Lava Core",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12364,    name = "Huge Emerald",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12800,    name = "Azerothian Diamond",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12809,    name = "Guardian Stone",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12811,    name = "Righteous Orb",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 13468,    name = "Black Lotus",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 17012,    name = "Core Leather",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21840,    name = "Bolt of Netherweave",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21877,    name = "Netherweave Cloth",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21881,    name = "Netherweb Spider Silk",       cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21882,    name = "Soul Essence",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 21887,    name = "Knothide Leather",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 22445,    name = "Arcane Dust",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14344,    name = "Large Brilliant Shard",       cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7076,     name = "Essence of Earth",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7078,     name = "Essence of Fire",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7080,     name = "Essence of Water",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7082,     name = "Essence of Air",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12360,    name = "Arcanite Bar",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12803,    name = "Living Essence",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12808,    name = "Essence of Undeath",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 16203,    name = "Greater Eternal Essence",     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 20520,    name = "Dark Rune",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12804,    name = "Powerful Mojo",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12810,    name = "Enchanted Leather",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14048,    name = "Bolt of Runecloth",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14342,    name = "Mooncloth",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 156930,   name = "Rich Illusion Dust",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 6037,     name = "Truesilver Bar",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7910,     name = "Star Ruby",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 12662,    name = "Demonic Rune",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4342,     name = "Purple Dye",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 8170,     name = "Rugged Leather",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 10290,    name = "Pink Dye",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14047,    name = "Runecloth",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14227,    name = "Ironweb Spider Silk",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14256,    name = "Felcloth",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 14341,    name = "Rune Thread",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 9210,     name = "Ghost Dye",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4339,     name = "Bolt of Mageweave",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7077,     name = "Heart of Fire",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7079,     name = "Globe of Water",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7972,     name = "Ichor of Undeath",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 10286,    name = "Heart of the Wild",           cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 8831,     name = "Purple Lotus",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4625,     name = "Firebloom",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 3864,     name = "Citrine",                     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7971,     name = "Black Pearl",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 8153,     name = "Wildvine",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 13926,    name = "Golden Pearl",                cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2325,     name = "Black Dye",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4304,     name = "Thick Leather",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4338,     name = "Mageweave Cloth",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 8343,     name = "Heavy Silken Thread",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 10285,    name = "Shadow Silk",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 1529,     name = "Jade",                        cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4305,     name = "Bolt of Silk Cloth",          cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4337,     name = "Thick Spider's Silk",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 6261,     name = "Orange Dye",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 3577,     name = "Gold Bar",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4234,     name = "Heavy Leather",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4291,     name = "Silken Thread",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4306,     name = "Silk Cloth",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7071,     name = "Iron Buckle",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 5500,     name = "Iridescent Pearl",            cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2997,     name = "Bolt of Woolen Cloth",        cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4340,     name = "Gray Dye",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 4341,     name = "Yellow Dye",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 6371,     name = "Fire Oil",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7067,     name = "Elemental Earth",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7068,     name = "Elemental Fire",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7069,     name = "Elemental Air",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7070,     name = "Elemental Water",             cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 7072,     name = "Naga Scale",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2319,     name = "Medium Leather",              cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2321,     name = "Fine Thread",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 3182,     name = "Spider's Silk",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 5498,     name = "Small Lustrous Pearl",        cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2592,     name = "Wool Cloth",                  cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2605,     name = "Green Dye",                   cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2318,     name = "Light Leather",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2604,     name = "Red Dye",                     cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2996,     name = "Bolt of Linen Cloth",         cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 6260,     name = "Blue Dye",                    cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2320,     name = "Coarse Thread",               cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2324,     name = "Bleach",                      cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 2589,     name = "Linen Cloth",                 cat = TG_CAT_TAILORING, skill = 1 },
    { tag = 18240,    name = "Ogre Tannin",                 cat = TG_CAT_TAILORING, skill = 1 }
}

TGT_PLUGIN_CATEGORIES = {
    { db = TG_DB_TAILORING, name = TG_CAT_TAILORING, smenu = TG_PREFIX_SHOW..TG_CAT_TAILORING, profession = "Tailoring", skill = 1 }
TGC_MINABLES = {}